FROM debian:stable-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install --yes \
    fs-uae \
    x11-utils \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir --parents /tmp/runtime-root && chmod 777 /tmp/runtime-root

WORKDIR /workspace

CMD ["sleep", "infinity"]

# Default command: run UAE in headless mode on a .uae config in /workspace/build/
#CMD ["bash", "-c", "uae-eadless /workspace/build/game.uae"]
